apiVersion: apps/v1
kind: Deployment
metadata:
    name: application-manager
spec:
    selector:
        matchLabels:
            app: application-manager
    replicas: 1
    template:
        metadata:
            labels:
                app: application-manager
        spec:
            containers:
                - image: 654654400574.dkr.ecr.ap-south-1.amazonaws.com/application-manager:latest
                  imagePullPolicy: Always
                  name: application-manager
                  ports:
                      - containerPort: 3002
