apiVersion: v1
kind: Service
metadata:
    name: classifier
spec:
    ports:
        - port: 80
          targetPort: 3005
          protocol: TCP
    type: ClusterIP
    selector:
        app: classifier
