apiVersion: apps/v1
kind: Deployment
metadata:
    name: classifier
spec:
    selector:
        matchLabels:
            app: classifier
    replicas: 1
    template:
        metadata:
            labels:
                app: classifier
        spec:
            containers:
                - image: 654654400574.dkr.ecr.ap-south-1.amazonaws.com/classifier:latest
                  imagePullPolicy: Always
                  name: classifier
                  ports:
                      - containerPort: 3006
