apiVersion: apps/v1
kind: Deployment
metadata:
    name: querier
spec:
    selector:
        matchLabels:
            app: querier
    replicas: 4
    template:
        metadata:
            labels:
                app: querier
        spec:
            containers:
                - image: 654654400574.dkr.ecr.ap-south-1.amazonaws.com/querier:dev
                  imagePullPolicy: Always
                  name: querier
                  ports:
                      - containerPort: 3006
