apiVersion: apps/v1
kind: Deployment
metadata:
    name: signature
spec:
    selector:
        matchLabels:
            app: signature
    replicas: 2
    template:
        metadata:
            labels:
                app: signature
        spec:
            containers:
                - image: 654654400574.dkr.ecr.ap-south-1.amazonaws.com/signature:prod
                  imagePullPolicy: Always
                  name: signature
                  ports:
                      - containerPort: 3008
