apiVersion: v1
kind: Service
metadata:
    name: signature
spec:
    ports:
        - port: 80
          targetPort: 3008
          protocol: TCP
    type: ClusterIP
    selector:
        app: signature
