apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: eks-test
    region: ap-south-1

managedNodeGroups:
    - name: ng-1
      instanceType: t2.medium
      minSize: 2
      maxSize: 2
      desiredCapacity: 2
      volumeSize: 20
