apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-nginx
spec:
    ingressClassName: nginx
    rules:
        - host: file.isree.dev
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: file-manager
                            port:
                                number: 80
        - host: auth.isree.dev
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: auth
                            port:
                                number: 80
        - host: application.isree.dev
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: application-manager
                            port:
                                number: 80
    # tls:
    # - hosts:
    #     - isree.dev
    #     secretName: example.com
