apiVersion: v1
kind: Service
metadata:
    name: application-manager-consumer
spec:
    ports:
        - port: 80
          targetPort: 3007
          protocol: TCP
    type: ClusterIP
    selector:
        app: application-manager-consumer
