apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: acme-crt
spec:
    secretName: acme-crt-secret
    dnsNames:
        - apiv2.neurofin.ai
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
