apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth
spec:
    selector:
        matchLabels:
            app: auth
    replicas: 2
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - image: 654654400574.dkr.ecr.ap-south-1.amazonaws.com/auth:prod
                  imagePullPolicy: Always
                  name: auth
                  ports:
                      - containerPort: 3002
