apiVersion: v1
kind: Service
metadata:
    name: textractor
spec:
    ports:
        - port: 80
          targetPort: 3004
          protocol: TCP
    type: ClusterIP
    selector:
        app: textractor
