# syntax=docker/dockerfile:1

# Build the application from source
FROM golang:alpine AS build-stage

WORKDIR /app

COPY . ./
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /build

# Deploy the application binary into a lean image
FROM alpine:latest AS build-release-stage

WORKDIR /

COPY --from=build-stage /build /build
COPY .env /

EXPOSE 3009

ENTRYPOINT ["/build"]
