apiVersion: v1
kind: Service
metadata:
    name: file-manager
spec:
    ports:
        - port: 80
          targetPort: 3001
          protocol: TCP
    type: ClusterIP
    selector:
        app: file-manager
