FROM python:3.11.4-alpine3.17

# set the current working dir to code
WORKDIR /code


# copy the file with requirements to code directory
COPY ./requirements.txt /requirements.txt

# install the package dependencies in the requirements file
RUN pip install --no-cache-dir --upgrade -r /requirements.txt


# copy the app inside the code directory
COPY . .

EXPOSE 3008

# 
CMD ["fastapi", "run", "main.py", "--port", "3008"]